# Generated by Django 4.0.1 on 2022-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='name',
            field=models.CharField(default='noname', max_length=256),
            preserve_default=False,
        ),
    ]
